import type { ComponentMeta } from '../types';

export const COMPONENT_META: ComponentMeta[] = [
  {
    type: 'client',
    label: 'Client',
    description: 'Browser, mobile app, or desktop application that users interact with',
    color: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.5)',
  },
  {
    type: 'server',
    label: 'Server',
    description: 'Application server that handles business logic and processes requests',
    color: '#00f5ff',
    glowColor: 'rgba(0, 245, 255, 0.5)',
  },
  {
    type: 'database',
    label: 'Database',
    description: 'Persistent storage for structured data (SQL/NoSQL)',
    color: '#ff00e5',
    glowColor: 'rgba(255, 0, 229, 0.5)',
  },
  {
    type: 'loadbalancer',
    label: 'Load Balancer',
    description: 'Distributes incoming traffic across multiple servers',
    color: '#ffd700',
    glowColor: 'rgba(255, 215, 0, 0.5)',
  },
  {
    type: 'cache',
    label: 'Cache',
    description: 'In-memory data store for fast access (Redis, Memcached)',
    color: '#00ff88',
    glowColor: 'rgba(0, 255, 136, 0.5)',
  },
  {
    type: 'queue',
    label: 'Message Queue',
    description: 'Asynchronous message broker (Kafka, RabbitMQ, SQS)',
    color: '#ff6b00',
    glowColor: 'rgba(255, 107, 0, 0.5)',
  },
  {
    type: 'api-gateway',
    label: 'API Gateway',
    description: 'Entry point that routes requests, handles auth, and rate limiting',
    color: '#8b5cf6',
    glowColor: 'rgba(139, 92, 246, 0.5)',
  },
  {
    type: 'cdn',
    label: 'CDN',
    description: 'Content Delivery Network for serving static assets globally',
    color: '#f472b6',
    glowColor: 'rgba(244, 114, 182, 0.5)',
  },
  {
    type: 'storage',
    label: 'Object Storage',
    description: 'Blob/file storage service (S3, GCS, Azure Blob)',
    color: '#a78bfa',
    glowColor: 'rgba(167, 139, 250, 0.5)',
  },
  {
    type: 'microservice',
    label: 'Microservice',
    description: 'Independent, deployable service handling a specific domain',
    color: '#34d399',
    glowColor: 'rgba(52, 211, 153, 0.5)',
  },
  {
    type: 'dns',
    label: 'DNS',
    description: 'Domain Name System for resolving domain names to IP addresses',
    color: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.5)',
  },
  {
    type: 'firewall',
    label: 'Firewall / WAF',
    description: 'Network security that monitors and filters incoming/outgoing traffic',
    color: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.5)',
  },
  {
    type: 'search-engine',
    label: 'Search Engine',
    description: 'Full-text search and analytics engine (Elasticsearch, Solr)',
    color: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.5)',
  },
  {
    type: 'notification',
    label: 'Notification',
    description: 'Push notification service for emails, SMS, and mobile alerts',
    color: '#ec4899',
    glowColor: 'rgba(236, 72, 153, 0.5)',
  },
  {
    type: 'scheduler',
    label: 'Task Scheduler',
    description: 'Cron jobs and scheduled task execution (Airflow, Celery Beat)',
    color: '#14b8a6',
    glowColor: 'rgba(20, 184, 166, 0.5)',
  },
  {
    type: 'auth-service',
    label: 'Auth Service',
    description: 'Identity, OAuth, JWT issuance and session verification (Auth0, Cognito)',
    color: '#fb7185',
    glowColor: 'rgba(251, 113, 133, 0.5)',
  },
  {
    type: 'payment-gateway',
    label: 'Payment Gateway',
    description: 'Secure payment processing and tokenization (Stripe, Adyen, PayPal)',
    color: '#4ade80',
    glowColor: 'rgba(74, 222, 128, 0.5)',
  },
  {
    type: 'ml-service',
    label: 'ML Service',
    description: 'Model inference and recommendation engine (TensorFlow Serving, Triton)',
    color: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.5)',
  },
  {
    type: 'websocket',
    label: 'WebSocket Server',
    description: 'Bidirectional real-time connections (Socket.IO, Pusher, Ably)',
    color: '#22d3ee',
    glowColor: 'rgba(34, 211, 238, 0.5)',
  },
  {
    type: 'rate-limiter',
    label: 'Rate Limiter',
    description: 'Throttles requests to prevent abuse (token bucket, leaky bucket)',
    color: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.5)',
  },
  {
    type: 'kubernetes',
    label: 'K8s Orchestrator',
    description: 'Container orchestration and pod scheduling (Kubernetes, ECS, Nomad)',
    color: '#60a5fa',
    glowColor: 'rgba(96, 165, 250, 0.5)',
  },
  {
    type: 'monitoring',
    label: 'Monitoring',
    description: 'Metrics, dashboards, alerting (Prometheus, Grafana, Datadog)',
    color: '#fde047',
    glowColor: 'rgba(253, 224, 71, 0.5)',
  },
  {
    type: 'log-aggregator',
    label: 'Log Aggregator',
    description: 'Centralized log ingestion and querying (ELK, Loki, Splunk)',
    color: '#94a3b8',
    glowColor: 'rgba(148, 163, 184, 0.5)',
  },
  {
    type: 'data-warehouse',
    label: 'Data Warehouse',
    description: 'Analytics-optimized columnar store (Snowflake, BigQuery, Redshift)',
    color: '#7dd3fc',
    glowColor: 'rgba(125, 211, 252, 0.5)',
  },
  {
    type: 'event-bus',
    label: 'Event Bus',
    description: 'Pub/sub event routing backbone (Kafka, EventBridge, Pulsar)',
    color: '#fb923c',
    glowColor: 'rgba(251, 146, 60, 0.5)',
  },
  {
    type: 'graphql',
    label: 'GraphQL Server',
    description: 'Unified query layer with typed schema (Apollo, Hasura, Relay)',
    color: '#e879f9',
    glowColor: 'rgba(232, 121, 249, 0.5)',
  },
  {
    type: 'session-store',
    label: 'Session Store',
    description: 'Distributed session/state storage (Redis, DynamoDB sessions)',
    color: '#84cc16',
    glowColor: 'rgba(132, 204, 22, 0.5)',
  },
  {
    type: 'vector-db',
    label: 'Vector DB',
    description: 'Embedding search for AI/RAG workloads (Pinecone, Weaviate, Milvus)',
    color: '#d946ef',
    glowColor: 'rgba(217, 70, 239, 0.5)',
  },
  {
    type: 'stream-processor',
    label: 'Stream Processor',
    description: 'Real-time data pipelines (Flink, Spark Streaming, Kafka Streams)',
    color: '#2dd4bf',
    glowColor: 'rgba(45, 212, 191, 0.5)',
  },
  {
    type: 'edge-worker',
    label: 'Edge Worker',
    description: 'Code at the edge / PoP (Cloudflare Workers, Lambda@Edge, Deno Deploy)',
    color: '#facc15',
    glowColor: 'rgba(250, 204, 21, 0.5)',
  },
  {
    type: 'analytics',
    label: 'Analytics Engine',
    description: 'Product analytics and event tracking (Mixpanel, Amplitude, GA)',
    color: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.5)',
  },
  {
    type: 'service-mesh',
    label: 'Service Mesh',
    description: 'Sidecar networking, mTLS, traffic policy (Istio, Linkerd, Consul)',
    color: '#a3e635',
    glowColor: 'rgba(163, 230, 53, 0.5)',
  },
  {
    type: 'blob-cdn',
    label: 'Media CDN',
    description: 'Optimized video/image streaming edge (Cloudflare Stream, Akamai)',
    color: '#f9a8d4',
    glowColor: 'rgba(249, 168, 212, 0.5)',
  },
  {
    type: 'reverse-proxy',
    label: 'Reverse Proxy',
    description: 'Request forwarding, TLS termination, caching (NGINX, Envoy, HAProxy)',
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.5)',
  },
  {
    type: 'secret-vault',
    label: 'Secret Vault',
    description: 'Encrypted credentials and key management (Vault, AWS KMS, Doppler)',
    color: '#eab308',
    glowColor: 'rgba(234, 179, 8, 0.5)',
  },
];

export function getComponentMeta(type: string): ComponentMeta {
  return COMPONENT_META.find(c => c.type === type) || COMPONENT_META[0];
}
