import { v4 as uuidv4 } from 'uuid';
import type { CanvasNode, Connection, DesignTemplate } from '../types';

export const TEMPLATES: DesignTemplate[] = [
  {
    id: 'basic-web',
    name: 'Basic Web App',
    description: 'Client -> Load Balancer -> Servers -> Database with Cache',
    icon: '🌐',
    difficulty: 'beginner',
    nodes: [
      { type: 'client', position: { x: 200, y: 80 }, label: 'Web Client' },
      { type: 'cdn', position: { x: 200, y: 180 }, label: 'CDN' },
      { type: 'loadbalancer', position: { x: 200, y: 290 }, label: 'Load Balancer' },
      { type: 'server', position: { x: 100, y: 400 }, label: 'Server 1' },
      { type: 'server', position: { x: 300, y: 400 }, label: 'Server 2' },
      { type: 'cache', position: { x: 400, y: 300 }, label: 'Redis Cache' },
      { type: 'database', position: { x: 200, y: 520 }, label: 'PostgreSQL' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'Static Assets', protocol: 'http' },
      { fromIndex: 0, toIndex: 2, label: 'API Requests', protocol: 'http' },
      { fromIndex: 2, toIndex: 3, label: 'Round Robin' },
      { fromIndex: 2, toIndex: 4, label: 'Round Robin' },
      { fromIndex: 3, toIndex: 5, label: 'Cache Read', protocol: 'tcp' },
      { fromIndex: 4, toIndex: 5, label: 'Cache Read', protocol: 'tcp' },
      { fromIndex: 3, toIndex: 6, label: 'SQL Queries', protocol: 'tcp' },
      { fromIndex: 4, toIndex: 6, label: 'SQL Queries', protocol: 'tcp' },
    ],
  },
  {
    id: 'chat-system',
    name: 'Chat System (WhatsApp-style)',
    description: 'Real-time messaging with WebSockets, message queue, and read receipts',
    icon: '💬',
    difficulty: 'intermediate',
    nodes: [
      { type: 'client', position: { x: 120, y: 80 }, label: 'Mobile App' },
      { type: 'client', position: { x: 320, y: 80 }, label: 'Web App' },
      { type: 'api-gateway', position: { x: 220, y: 190 }, label: 'API Gateway' },
      { type: 'server', position: { x: 100, y: 310 }, label: 'Chat Service' },
      { type: 'server', position: { x: 340, y: 310 }, label: 'Presence Service' },
      { type: 'queue', position: { x: 220, y: 420 }, label: 'Kafka' },
      { type: 'cache', position: { x: 440, y: 420 }, label: 'Redis (Sessions)' },
      { type: 'database', position: { x: 100, y: 530 }, label: 'Messages DB' },
      { type: 'storage', position: { x: 340, y: 530 }, label: 'Media Storage (S3)' },
      { type: 'microservice', position: { x: 500, y: 310 }, label: 'Notification Svc' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 2, label: 'WebSocket', protocol: 'websocket' },
      { fromIndex: 1, toIndex: 2, label: 'WebSocket', protocol: 'websocket' },
      { fromIndex: 2, toIndex: 3, label: 'Route', protocol: 'grpc' },
      { fromIndex: 2, toIndex: 4, label: 'Heartbeat', protocol: 'grpc' },
      { fromIndex: 3, toIndex: 5, label: 'Publish', protocol: 'amqp' },
      { fromIndex: 4, toIndex: 6, label: 'Online Status', protocol: 'tcp' },
      { fromIndex: 5, toIndex: 7, label: 'Persist', protocol: 'tcp' },
      { fromIndex: 3, toIndex: 8, label: 'Upload', protocol: 'http' },
      { fromIndex: 5, toIndex: 9, label: 'Push Notify', protocol: 'amqp' },
    ],
  },
  {
    id: 'social-feed',
    name: 'Social Media Feed (Twitter-style)',
    description: 'News feed generation with fan-out, search, and media pipeline',
    icon: '📱',
    difficulty: 'advanced',
    nodes: [
      { type: 'client', position: { x: 250, y: 60 }, label: 'Client App' },
      { type: 'cdn', position: { x: 450, y: 60 }, label: 'CDN' },
      { type: 'api-gateway', position: { x: 250, y: 170 }, label: 'API Gateway' },
      { type: 'loadbalancer', position: { x: 250, y: 270 }, label: 'Load Balancer' },
      { type: 'server', position: { x: 100, y: 370 }, label: 'Post Service' },
      { type: 'server', position: { x: 280, y: 370 }, label: 'Feed Service' },
      { type: 'server', position: { x: 460, y: 370 }, label: 'User Service' },
      { type: 'queue', position: { x: 100, y: 480 }, label: 'Fan-out Queue' },
      { type: 'cache', position: { x: 280, y: 480 }, label: 'Feed Cache' },
      { type: 'database', position: { x: 100, y: 590 }, label: 'Posts DB' },
      { type: 'database', position: { x: 320, y: 590 }, label: 'Social Graph DB' },
      { type: 'storage', position: { x: 500, y: 490 }, label: 'Media Storage' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'Static', protocol: 'http' },
      { fromIndex: 0, toIndex: 2, label: 'API', protocol: 'http' },
      { fromIndex: 2, toIndex: 3, label: 'Route' },
      { fromIndex: 3, toIndex: 4, label: 'Create Post', protocol: 'grpc' },
      { fromIndex: 3, toIndex: 5, label: 'Get Feed', protocol: 'grpc' },
      { fromIndex: 3, toIndex: 6, label: 'Auth', protocol: 'grpc' },
      { fromIndex: 4, toIndex: 7, label: 'Fan-out', protocol: 'amqp' },
      { fromIndex: 5, toIndex: 8, label: 'Read Cache', protocol: 'tcp' },
      { fromIndex: 7, toIndex: 9, label: 'Persist', protocol: 'tcp' },
      { fromIndex: 7, toIndex: 8, label: 'Update Feed', protocol: 'tcp' },
      { fromIndex: 6, toIndex: 10, label: 'Followers', protocol: 'tcp' },
      { fromIndex: 4, toIndex: 11, label: 'Upload', protocol: 'http' },
    ],
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce Platform',
    description: 'Product catalog, cart, payment, and order fulfillment pipeline',
    icon: '🛒',
    difficulty: 'advanced',
    nodes: [
      { type: 'client', position: { x: 300, y: 50 }, label: 'Storefront' },
      { type: 'dns', position: { x: 500, y: 50 }, label: 'DNS' },
      { type: 'cdn', position: { x: 140, y: 50 }, label: 'CDN' },
      { type: 'firewall', position: { x: 300, y: 150 }, label: 'WAF' },
      { type: 'api-gateway', position: { x: 300, y: 250 }, label: 'API Gateway' },
      { type: 'loadbalancer', position: { x: 300, y: 350 }, label: 'Load Balancer' },
      { type: 'microservice', position: { x: 100, y: 450 }, label: 'Product Service' },
      { type: 'microservice', position: { x: 300, y: 450 }, label: 'Cart Service' },
      { type: 'microservice', position: { x: 500, y: 450 }, label: 'Payment Service' },
      { type: 'search-engine', position: { x: 100, y: 570 }, label: 'Elasticsearch' },
      { type: 'cache', position: { x: 300, y: 570 }, label: 'Redis' },
      { type: 'database', position: { x: 500, y: 570 }, label: 'Orders DB' },
      { type: 'queue', position: { x: 300, y: 680 }, label: 'Order Queue' },
      { type: 'notification', position: { x: 500, y: 680 }, label: 'Email/SMS' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'Resolve', protocol: 'http' },
      { fromIndex: 0, toIndex: 2, label: 'Assets', protocol: 'http' },
      { fromIndex: 0, toIndex: 3, label: 'Requests', protocol: 'http' },
      { fromIndex: 3, toIndex: 4, label: 'Filtered', protocol: 'http' },
      { fromIndex: 4, toIndex: 5, label: 'Route', protocol: 'http' },
      { fromIndex: 5, toIndex: 6, label: 'Catalog', protocol: 'grpc' },
      { fromIndex: 5, toIndex: 7, label: 'Cart Ops', protocol: 'grpc' },
      { fromIndex: 5, toIndex: 8, label: 'Checkout', protocol: 'grpc' },
      { fromIndex: 6, toIndex: 9, label: 'Index', protocol: 'http' },
      { fromIndex: 7, toIndex: 10, label: 'Session', protocol: 'tcp' },
      { fromIndex: 8, toIndex: 11, label: 'Store Order', protocol: 'tcp' },
      { fromIndex: 8, toIndex: 12, label: 'Fulfill', protocol: 'amqp' },
      { fromIndex: 12, toIndex: 13, label: 'Confirm', protocol: 'amqp' },
    ],
  },
  {
    id: 'video-streaming',
    name: 'Video Streaming (Netflix-style)',
    description: 'Video encoding, CDN delivery, and recommendation engine',
    icon: '🎬',
    difficulty: 'advanced',
    nodes: [
      { type: 'client', position: { x: 300, y: 50 }, label: 'Video Player' },
      { type: 'dns', position: { x: 500, y: 50 }, label: 'DNS' },
      { type: 'cdn', position: { x: 100, y: 150 }, label: 'Video CDN' },
      { type: 'api-gateway', position: { x: 300, y: 150 }, label: 'API Gateway' },
      { type: 'loadbalancer', position: { x: 300, y: 260 }, label: 'Load Balancer' },
      { type: 'microservice', position: { x: 100, y: 370 }, label: 'Catalog Service' },
      { type: 'microservice', position: { x: 300, y: 370 }, label: 'Streaming Service' },
      { type: 'microservice', position: { x: 500, y: 370 }, label: 'Recommend Svc' },
      { type: 'queue', position: { x: 100, y: 490 }, label: 'Encoding Queue' },
      { type: 'scheduler', position: { x: 300, y: 490 }, label: 'Transcoder' },
      { type: 'storage', position: { x: 500, y: 490 }, label: 'Video Storage' },
      { type: 'database', position: { x: 100, y: 600 }, label: 'Metadata DB' },
      { type: 'cache', position: { x: 300, y: 600 }, label: 'Session Cache' },
      { type: 'database', position: { x: 500, y: 600 }, label: 'User Prefs DB' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'Resolve', protocol: 'http' },
      { fromIndex: 0, toIndex: 2, label: 'Stream', protocol: 'http' },
      { fromIndex: 0, toIndex: 3, label: 'API', protocol: 'http' },
      { fromIndex: 3, toIndex: 4, label: 'Route' },
      { fromIndex: 4, toIndex: 5, label: 'Browse', protocol: 'grpc' },
      { fromIndex: 4, toIndex: 6, label: 'Play', protocol: 'grpc' },
      { fromIndex: 4, toIndex: 7, label: 'Suggest', protocol: 'grpc' },
      { fromIndex: 5, toIndex: 8, label: 'Encode', protocol: 'amqp' },
      { fromIndex: 8, toIndex: 9, label: 'Process', protocol: 'amqp' },
      { fromIndex: 9, toIndex: 10, label: 'Store', protocol: 'http' },
      { fromIndex: 6, toIndex: 10, label: 'Fetch', protocol: 'http' },
      { fromIndex: 5, toIndex: 11, label: 'Query', protocol: 'tcp' },
      { fromIndex: 6, toIndex: 12, label: 'Session', protocol: 'tcp' },
      { fromIndex: 7, toIndex: 13, label: 'Prefs', protocol: 'tcp' },
    ],
  },
  {
    id: 'payment-system',
    name: 'Payment Processing',
    description: 'Secure payment flow with fraud detection and ledger system',
    icon: '💳',
    difficulty: 'intermediate',
    nodes: [
      { type: 'client', position: { x: 250, y: 60 }, label: 'Checkout UI' },
      { type: 'firewall', position: { x: 250, y: 160 }, label: 'WAF / PCI' },
      { type: 'api-gateway', position: { x: 250, y: 260 }, label: 'Payment Gateway' },
      { type: 'microservice', position: { x: 100, y: 370 }, label: 'Auth Service' },
      { type: 'microservice', position: { x: 250, y: 370 }, label: 'Payment Service' },
      { type: 'microservice', position: { x: 430, y: 370 }, label: 'Fraud Detection' },
      { type: 'queue', position: { x: 250, y: 480 }, label: 'Transaction Queue' },
      { type: 'database', position: { x: 100, y: 580 }, label: 'Ledger DB' },
      { type: 'cache', position: { x: 430, y: 480 }, label: 'Rate Limiter' },
      { type: 'notification', position: { x: 430, y: 580 }, label: 'Receipt/Alert' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'HTTPS', protocol: 'http' },
      { fromIndex: 1, toIndex: 2, label: 'Filtered', protocol: 'http' },
      { fromIndex: 2, toIndex: 3, label: 'Verify', protocol: 'grpc' },
      { fromIndex: 2, toIndex: 4, label: 'Charge', protocol: 'grpc' },
      { fromIndex: 4, toIndex: 5, label: 'Check', protocol: 'grpc' },
      { fromIndex: 4, toIndex: 6, label: 'Enqueue', protocol: 'amqp' },
      { fromIndex: 6, toIndex: 7, label: 'Record', protocol: 'tcp' },
      { fromIndex: 5, toIndex: 8, label: 'Throttle', protocol: 'tcp' },
      { fromIndex: 6, toIndex: 9, label: 'Notify', protocol: 'amqp' },
    ],
  },
  {
    id: 'search-platform',
    name: 'Search Platform',
    description: 'Distributed search with indexing pipeline and relevance ranking',
    icon: '🔍',
    difficulty: 'intermediate',
    nodes: [
      { type: 'client', position: { x: 250, y: 60 }, label: 'Search UI' },
      { type: 'api-gateway', position: { x: 250, y: 160 }, label: 'API Gateway' },
      { type: 'loadbalancer', position: { x: 250, y: 260 }, label: 'Load Balancer' },
      { type: 'microservice', position: { x: 100, y: 370 }, label: 'Query Service' },
      { type: 'microservice', position: { x: 400, y: 370 }, label: 'Indexer Service' },
      { type: 'search-engine', position: { x: 100, y: 480 }, label: 'Elasticsearch' },
      { type: 'cache', position: { x: 250, y: 480 }, label: 'Query Cache' },
      { type: 'queue', position: { x: 400, y: 480 }, label: 'Index Queue' },
      { type: 'database', position: { x: 250, y: 590 }, label: 'Content DB' },
      { type: 'scheduler', position: { x: 400, y: 590 }, label: 'Reindex Cron' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'Search', protocol: 'http' },
      { fromIndex: 1, toIndex: 2, label: 'Route' },
      { fromIndex: 2, toIndex: 3, label: 'Query', protocol: 'grpc' },
      { fromIndex: 2, toIndex: 4, label: 'Index', protocol: 'grpc' },
      { fromIndex: 3, toIndex: 5, label: 'Search', protocol: 'http' },
      { fromIndex: 3, toIndex: 6, label: 'Cache Hit', protocol: 'tcp' },
      { fromIndex: 4, toIndex: 7, label: 'Queue Docs', protocol: 'amqp' },
      { fromIndex: 7, toIndex: 5, label: 'Index', protocol: 'http' },
      { fromIndex: 4, toIndex: 8, label: 'Read', protocol: 'tcp' },
      { fromIndex: 9, toIndex: 4, label: 'Trigger', protocol: 'http' },
    ],
  },
  {
    id: 'notification-system',
    name: 'Notification System',
    description: 'Multi-channel notification pipeline with priority routing',
    icon: '🔔',
    difficulty: 'beginner',
    nodes: [
      { type: 'microservice', position: { x: 250, y: 60 }, label: 'Event Source' },
      { type: 'api-gateway', position: { x: 250, y: 160 }, label: 'Notification API' },
      { type: 'queue', position: { x: 250, y: 270 }, label: 'Priority Queue' },
      { type: 'microservice', position: { x: 80, y: 380 }, label: 'Email Worker' },
      { type: 'microservice', position: { x: 250, y: 380 }, label: 'SMS Worker' },
      { type: 'microservice', position: { x: 420, y: 380 }, label: 'Push Worker' },
      { type: 'notification', position: { x: 80, y: 490 }, label: 'SMTP Relay' },
      { type: 'notification', position: { x: 250, y: 490 }, label: 'Twilio' },
      { type: 'notification', position: { x: 420, y: 490 }, label: 'Firebase FCM' },
      { type: 'database', position: { x: 250, y: 600 }, label: 'Delivery Log' },
      { type: 'cache', position: { x: 420, y: 600 }, label: 'User Prefs Cache' },
    ],
    connections: [
      { fromIndex: 0, toIndex: 1, label: 'Events', protocol: 'http' },
      { fromIndex: 1, toIndex: 2, label: 'Enqueue', protocol: 'amqp' },
      { fromIndex: 2, toIndex: 3, label: 'Email', protocol: 'amqp' },
      { fromIndex: 2, toIndex: 4, label: 'SMS', protocol: 'amqp' },
      { fromIndex: 2, toIndex: 5, label: 'Push', protocol: 'amqp' },
      { fromIndex: 3, toIndex: 6, label: 'Send', protocol: 'tcp' },
      { fromIndex: 4, toIndex: 7, label: 'Send', protocol: 'http' },
      { fromIndex: 5, toIndex: 8, label: 'Send', protocol: 'http' },
      { fromIndex: 3, toIndex: 9, label: 'Log', protocol: 'tcp' },
      { fromIndex: 4, toIndex: 9, label: 'Log', protocol: 'tcp' },
      { fromIndex: 5, toIndex: 10, label: 'Prefs', protocol: 'tcp' },
    ],
  },
];

export function instantiateTemplate(template: DesignTemplate): {
  nodes: CanvasNode[];
  connections: Connection[];
} {
  const nodes: CanvasNode[] = template.nodes.map(n => ({
    ...n,
    id: uuidv4(),
  }));

  const connections: Connection[] = template.connections
    .filter(c => c.fromIndex < nodes.length && c.toIndex < nodes.length)
    .map(c => ({
      id: uuidv4(),
      from: nodes[c.fromIndex].id,
      to: nodes[c.toIndex].id,
      label: c.label,
      protocol: c.protocol,
      animated: true,
    }));

  return { nodes, connections };
}
